# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 10:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_auto_20161022_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colour_class',
            new_name='colour_code',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_max',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_min',
        ),
        migrations.AddField(
            model_name='colourclass',
            name='colour_code',
            field=models.CharField(default='red', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colourclass',
            name='description',
            field=models.CharField(default='description', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 25, 10, 15, 1, 39442, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 25, 10, 15, 52, 487713, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comments',
            field=models.CharField(default='comments', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_id',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.CharField(default='desc', max_length=50),
            preserve_default=False,
        ),
    ]
