# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_auto_20161025_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
