# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_newrelease'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrelease',
            name='image',
            field=models.ImageField(null='True', upload_to='images/'),
        ),
    ]
