# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0005_newrelease_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrelease',
            name='image',
            field=models.ImageField(null='True', upload_to='wholesale/static/wholesale/images/'),
        ),
    ]
