# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0007_auto_20161112_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrelease',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
