# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-14 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0009_auto_20161114_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrelease',
            name='height_field',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='newrelease',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='newrelease',
            name='width_field',
            field=models.IntegerField(default=100),
        ),
    ]
