# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wholesale', '0013_auto_20161116_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Item',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('flowers_names', models.CharField(max_length=1000000)),
                ('quantity_list', models.CharField(max_length=1000000)),
                ('total_price', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
