# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0015_auto_20161125_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order_item',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
