# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0016_auto_20161125_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='order_id'),
        ),
    ]
