# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0017_auto_20161125_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='price',
            field=models.IntegerField(default=0, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='order_item',
            name='timestamp',
            field=models.DateTimeField(null=True, verbose_name='created on'),
        ),
    ]
