# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-25 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0018_auto_20161125_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='price',
            field=models.CharField(max_length=100000, verbose_name='price'),
        ),
    ]
