# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0019_auto_20161125_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrelease',
            name='description',
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
