# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0021_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='post_code',
            field=models.IntegerField(null=True, verbose_name='post_code'),
        ),
    ]
