# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0022_auto_20161129_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=10000000, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='post_code',
            field=models.CharField(max_length=10000000, null=True, verbose_name='post_code'),
        ),
    ]
