# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0023_auto_20161129_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='delivery',
        ),
    ]
